package ru.yandex.practicum.java.tasktracker.utils;

public enum ResultOfOperation {
    SUCCESS,
    ERROR_ID_LESS_ZERO,
    ERROR_OBJECT_NULL,
    ERROR_OBJECT_FIELDS_NULL,
    ERROR_OBJECT_NOT_FOUND,
    ERROR_OBJECT_ALREADY_EXISTS,
    ERROR_OBJECT_ILLEGAL,
    ERROR_SUBTASK_NOT_FOUND,
    ERROR_SUBTASKS_NOT_EMPTY,
    ERROR_MISMATCH_PARENT_ID,
    ERROR_NO_AVAILABLE_ID,
    ERROR_DURATION_LESS_ZERO,
    ERROR_START_NOT_SET,
    ERROR_INTERSECT_TIME
}
